name: ADC
url: "http://www.ti.com/product/ads7830"
addresses: [0x48]

command:
    default: 0b10000000

    7:
        name: SD
        length: 1
        values:
            0: DIFFERENTIAL
            1: SINGLE_ENDED
    6: #[6:4]
        name: CHANNEL
            length: 3
            # Selection of C2-C0 bits, control selection ADC channel
            # Shifted by 4 due to location in CMD byte.
               
    # Manual lists [3,2] as PD, split up for clarity.
    # Consider re-merging them if this doesn't work.
    3: 
        name: INTERNAL_REF
        length: 1
            values: 
                0: OFF
                1: ON
    2:
        name: AD_CONV        
        length: 1
        values:
            0: OFF
            1: ON
 registers:
    0x00:
        name: CH0
        access: [read]
        type: uint8
    0x10:
        name: CH1
        access: [read]
        type: uint8
    0x20:
        name: CH2
        access: [read]
        type: uint8
    0x30:
        name: 3
        access: [read]
        type: uint8
    0x40:
        name: CH4
        access: [read]
        type: uint8
    0x50:
        name: CH5
        access: [read]
        type: uint8
    0x60:
        name: CH6
        access: [read]
        type: uint8
    0x70
        name: CH7
        access: [read]
        type: uint8
    
