name: ADC
url: "http://www.ti.com/product/ads7830"
addresses: [0x48]

command:
    default: 0b10000000


registers:
    0x00 << 4:
        name: CH0
        access: [read]
        type: uint8
    0x01 << 4:
        name: CH1
        access: [read]
        type: uint8
    0x02 << 4:
        name: CH2
        access: [read]
        type: uint8
    0x03 << 4:
        name: 3
        access: [read]
        type: uint8
    0x04 << 4:
        name: CH4
        access: [read]
        type: uint8
    0x05 << 4:
        name: CH5
        access: [read]
        type: uint8
    0x06 << 4:
        name: CH6
        access: [read]
        type: uint8
    0x07 << 4:
        name: CH7
        access: [read]
        type: uint8